# // TODO: Implementar el docker-compose
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria_app
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/data

volumes:
  h2_data: